
The following have been reloaded with a version change:
  1) python/.3.11.4 => python/3.11.4

INFO:    gocryptfs not found, will not be able to use gocryptfs
INFO:root:Extracted GTF attributes: ['transcript_id', 'gene_id']
Traceback (most recent call last):
  File "./00_scripts/07_make_pacbio_cds_gtf.py", line 143, in <module>
    main()
  File "./00_scripts/07_make_pacbio_cds_gtf.py", line 140, in main
    make_pacbio_cds_gtf(results.sample_gtf, results.agg_orfs, results.refined_orfs, results.pb_gene, results.output_cds)
  File "./00_scripts/07_make_pacbio_cds_gtf.py", line 109, in make_pacbio_cds_gtf
    gene = pb_gene[acc]
KeyError: 'PB.1007.42'
INFO:    gocryptfs not found, will not be able to use gocryptfs
INFO:root:Extracted GTF attributes: ['transcript_id', 'gene_id']
Traceback (most recent call last):
  File "./00_scripts/07_make_pacbio_cds_gtf.py", line 143, in <module>
    main()
  File "./00_scripts/07_make_pacbio_cds_gtf.py", line 140, in main
    make_pacbio_cds_gtf(results.sample_gtf, results.agg_orfs, results.refined_orfs, results.pb_gene, results.output_cds)
  File "./00_scripts/07_make_pacbio_cds_gtf.py", line 109, in make_pacbio_cds_gtf
    gene = pb_gene[acc]
KeyError: 'PB.1004.4'
