
The following have been reloaded with a version change:
  1) python/.3.11.4 => python/3.11.4

INFO:root:Loading data...
INFO:root:Extracted GTF attributes: ['gene_id', 'gene_type', 'gene_name', 'level', 'mgi_id', 'havana_gene', 'transcript_id', 'transcript_type', 'transcript_name', 'transcript_support_level', 'tag', 'havana_transcript', 'exon_number', 'exon_id', 'protein_id', 'ccdsid', 'ont']
INFO:root:Extracted GTF attributes: ['transcript_id', 'gene_id', 'gene_name']
INFO:root:Mapping ORFs to gencode...
INFO:root:Mapping plus strands...
Empty DataFrame
Columns: [ID, pb_acc, misc, orf]
Index: []
  seqname  ...                     gene_name
0    chr1  ...                         10453
1    chr1  ...                         10453
2    chr1  ...  ENSMUSG00000033845.14_Mrpl15
3    chr1  ...  ENSMUSG00000033845.14_Mrpl15
4    chr1  ...  ENSMUSG00000033845.14_Mrpl15

[5 rows x 11 columns]
['gene' 'transcript' 'exon' 'CDS' 'start_codon' 'stop_codon' 'UTR'
 'Selenocysteine']
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/opt/conda/envs/lrpg/lib/python3.7/multiprocessing/pool.py", line 121, in worker
    result = (True, func(*args, **kwds))
  File "/opt/conda/envs/lrpg/lib/python3.7/multiprocessing/pool.py", line 47, in starmapstar
    return list(itertools.starmap(args[0], args[1]))
  File "00_scripts/05_mando_orf_calling.py", line 97, in plus_mapping_single_chromosome
    plus_exons['current_size'] = plus_exons.sort_values(by = ['transcript_id', 'exon_start']).groupby('transcript_id')['exon_length'].cumsum()
  File "/opt/conda/envs/lrpg/lib/python3.7/site-packages/pandas/core/frame.py", line 5439, in sort_values
    keys = [self._get_label_or_level_values(x, axis=axis) for x in by]
  File "/opt/conda/envs/lrpg/lib/python3.7/site-packages/pandas/core/frame.py", line 5439, in <listcomp>
    keys = [self._get_label_or_level_values(x, axis=axis) for x in by]
  File "/opt/conda/envs/lrpg/lib/python3.7/site-packages/pandas/core/generic.py", line 1681, in _get_label_or_level_values
    raise KeyError(key)
KeyError: 'exon_start'
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "00_scripts/05_mando_orf_calling.py", line 302, in <module>
    main()
  File "00_scripts/05_mando_orf_calling.py", line 277, in main
    all_orfs = orf_mapping(orf_coord, gencode, sample_gtf, orf_seq, pool, results.num_cores)
  File "00_scripts/05_mando_orf_calling.py", line 81, in orf_mapping
    plus = plus_mapping(exons, orf_coord, start_codons, pool, num_cores)
  File "00_scripts/05_mando_orf_calling.py", line 131, in plus_mapping
    plus_orf_list = pool.starmap(plus_mapping_single_chromosome, iterable)
  File "/opt/conda/envs/lrpg/lib/python3.7/multiprocessing/pool.py", line 276, in starmap
    return self._map_async(func, iterable, starmapstar, chunksize).get()
  File "/opt/conda/envs/lrpg/lib/python3.7/multiprocessing/pool.py", line 657, in get
    raise self._value
KeyError: 'exon_start'
INFO:root:Loading data...
Traceback (most recent call last):
  File "00_scripts/05_orf_calling.py", line 307, in <module>
    main()
  File "00_scripts/05_orf_calling.py", line 267, in main
    orf_coord = read_orf(results.orf_coord)
  File "00_scripts/05_orf_calling.py", line 188, in read_orf
    orf[['pb_acc', 'misc', 'orf']] = orf['ID'].str.split('_', expand=True)
  File "/opt/conda/envs/lrpg/lib/python3.7/site-packages/pandas/core/frame.py", line 3160, in __setitem__
    self._setitem_array(key, value)
  File "/opt/conda/envs/lrpg/lib/python3.7/site-packages/pandas/core/frame.py", line 3186, in _setitem_array
    raise ValueError("Columns must be same length as key")
ValueError: Columns must be same length as key
